
server:
  port: 8081

spring:
  application:
    name: articles
  datasource:
    url: jdbc:postgresql://postgres:5432/articledb
    username: 'postgres'
    password: 'abcd1234'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
  rabbitmq:
    host: 172.23.0.3
    port: 5672
    username: admin
    password: admin

logging:
  level:
    org.hibernate.SQL: DEBUG

